services:
  hunyuan3d:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hunyuan3d21:latest
    container_name: hy3d21
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    volumes:
      # Montage du fichier du modèle (Host -> Conteneur en lecture seule)
      - /home/vrd/.cache/huggingface/hub/models--tencent--Hunyuan3D-2.1/snapshots/0b94677654c57bb9a6b6845cd7b704ccf551d327/hunyuan3d-dit-v2-1/:/root/.cache/hy3dgen/tencent/Hunyuan3D-2.1/hunyuan3d-dit-v2-1/
    command: ["python", "gradio_app.py", "--port", "7860"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
